/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadora;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

/**
 *
 * @author Marcus
 */
public class Calculadora extends javax.swing.JFrame {
    
    ScriptEngineManager sem =new ScriptEngineManager();
    ScriptEngine se = sem.getEngineByName("JavaScript");

    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtoperacion = new javax.swing.JLabel();
        txtresultado = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btigual = new javax.swing.JButton();
        btprc = new javax.swing.JButton();
        btexp = new javax.swing.JButton();
        btdv = new javax.swing.JButton();
        btmltp = new javax.swing.JButton();
        btmn = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        btc = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btpt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtoperacion.setBackground(new java.awt.Color(0, 0, 0));
        txtoperacion.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        txtoperacion.setForeground(new java.awt.Color(0, 0, 0));
        txtoperacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtoperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 30));

        txtresultado.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        txtresultado.setForeground(new java.awt.Color(0, 0, 0));
        txtresultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 150));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btigual.setBackground(new java.awt.Color(204, 204, 204));
        btigual.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btigual.setForeground(new java.awt.Color(51, 51, 51));
        btigual.setText("=");
        btigual.setFocusPainted(false);
        btigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigualActionPerformed(evt);
            }
        });
        jPanel2.add(btigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 50, 40));

        btprc.setBackground(new java.awt.Color(204, 204, 204));
        btprc.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btprc.setForeground(new java.awt.Color(51, 51, 51));
        btprc.setText("%");
        btprc.setFocusPainted(false);
        btprc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btprcActionPerformed(evt);
            }
        });
        jPanel2.add(btprc, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 50, 40));

        btexp.setBackground(new java.awt.Color(204, 204, 204));
        btexp.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        btexp.setForeground(new java.awt.Color(51, 51, 51));
        btexp.setText("CE");
        btexp.setFocusPainted(false);
        btexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexpActionPerformed(evt);
            }
        });
        jPanel2.add(btexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, 40));

        btdv.setBackground(new java.awt.Color(204, 204, 204));
        btdv.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btdv.setForeground(new java.awt.Color(51, 51, 51));
        btdv.setText("/");
        btdv.setFocusPainted(false);
        btdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdvActionPerformed(evt);
            }
        });
        jPanel2.add(btdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 50, 40));

        btmltp.setBackground(new java.awt.Color(204, 204, 204));
        btmltp.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btmltp.setForeground(new java.awt.Color(51, 51, 51));
        btmltp.setText("X");
        btmltp.setFocusPainted(false);
        btmltp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmltpActionPerformed(evt);
            }
        });
        jPanel2.add(btmltp, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 50, 40));

        btmn.setBackground(new java.awt.Color(204, 204, 204));
        btmn.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btmn.setForeground(new java.awt.Color(51, 51, 51));
        btmn.setText("-");
        btmn.setFocusPainted(false);
        btmn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmnActionPerformed(evt);
            }
        });
        jPanel2.add(btmn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 50, 40));

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(51, 51, 51));
        jButton8.setText("+");
        jButton8.setFocusPainted(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 40));

        btc.setBackground(new java.awt.Color(204, 204, 204));
        btc.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btc.setForeground(new java.awt.Color(51, 51, 51));
        btc.setText("C");
        btc.setFocusPainted(false);
        btc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcActionPerformed(evt);
            }
        });
        jPanel2.add(btc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 50, 40));

        bt9.setBackground(new java.awt.Color(227, 231, 231));
        bt9.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt9.setForeground(new java.awt.Color(51, 51, 51));
        bt9.setText("9");
        bt9.setFocusPainted(false);
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel2.add(bt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 50, 40));

        bt7.setBackground(new java.awt.Color(227, 231, 231));
        bt7.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt7.setForeground(new java.awt.Color(51, 51, 51));
        bt7.setText("7");
        bt7.setFocusPainted(false);
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel2.add(bt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, 40));

        bt8.setBackground(new java.awt.Color(227, 231, 231));
        bt8.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt8.setForeground(new java.awt.Color(51, 51, 51));
        bt8.setText("8");
        bt8.setFocusPainted(false);
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel2.add(bt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, 40));

        bt4.setBackground(new java.awt.Color(227, 231, 231));
        bt4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt4.setForeground(new java.awt.Color(51, 51, 51));
        bt4.setText("4");
        bt4.setFocusPainted(false);
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel2.add(bt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 40));

        bt5.setBackground(new java.awt.Color(227, 231, 231));
        bt5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt5.setForeground(new java.awt.Color(51, 51, 51));
        bt5.setText("5");
        bt5.setFocusPainted(false);
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel2.add(bt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 50, 40));

        bt6.setBackground(new java.awt.Color(227, 231, 231));
        bt6.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt6.setForeground(new java.awt.Color(51, 51, 51));
        bt6.setText("6");
        bt6.setFocusPainted(false);
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel2.add(bt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 50, 40));

        bt1.setBackground(new java.awt.Color(227, 231, 231));
        bt1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt1.setForeground(new java.awt.Color(51, 51, 51));
        bt1.setText("1");
        bt1.setFocusPainted(false);
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel2.add(bt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 50, 40));

        bt2.setBackground(new java.awt.Color(227, 231, 231));
        bt2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(51, 51, 51));
        bt2.setText("2");
        bt2.setFocusPainted(false);
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel2.add(bt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 50, 40));

        bt3.setBackground(new java.awt.Color(227, 231, 231));
        bt3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt3.setForeground(new java.awt.Color(51, 51, 51));
        bt3.setText("3");
        bt3.setFocusPainted(false);
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel2.add(bt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 50, 40));

        bt0.setBackground(new java.awt.Color(227, 231, 231));
        bt0.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        bt0.setForeground(new java.awt.Color(51, 51, 51));
        bt0.setText("0");
        bt0.setFocusPainted(false);
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel2.add(bt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 50, 40));

        btpt.setBackground(new java.awt.Color(227, 231, 231));
        btpt.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        btpt.setForeground(new java.awt.Color(51, 51, 51));
        btpt.setText(".");
        btpt.setFocusPainted(false);
        btpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btptActionPerformed(evt);
            }
        });
        jPanel2.add(btpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 50, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 340, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
        String resultado;
        try {
            resultado = se.eval(txtoperacion.getText()).toString();
            txtresultado.setText(resultado);
        } catch (ScriptException ex) {
            
        }
            
    }//GEN-LAST:event_btigualActionPerformed

    private void btprcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btprcActionPerformed
        addNumber("%");
        
    }//GEN-LAST:event_btprcActionPerformed

    private void btexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexpActionPerformed
        String texto = txtoperacion.getText().substring(0,txtoperacion.getText().length()-1);
        txtoperacion.setText(texto);
        btigual.doClick();
    }//GEN-LAST:event_btexpActionPerformed

    private void btdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdvActionPerformed
        addNumber("/");
        
    }//GEN-LAST:event_btdvActionPerformed

    private void btmltpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmltpActionPerformed
        addNumber("*");
        btigual.doClick();
    }//GEN-LAST:event_btmltpActionPerformed

    private void btmnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmnActionPerformed
        addNumber("-");
        
    }//GEN-LAST:event_btmnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        addNumber("+");
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcActionPerformed
        txtoperacion.setText("");
        txtresultado.setText("");
    }//GEN-LAST:event_btcActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        addNumber("9");
        btigual.doClick();
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        addNumber("7");
        btigual.doClick();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        addNumber("8");
        btigual.doClick();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        addNumber("4");
        btigual.doClick();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        addNumber("5");
        btigual.doClick();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        addNumber("6");
        btigual.doClick();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        addNumber("1");
        btigual.doClick();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        addNumber("2");
        btigual.doClick();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        addNumber("3");
        btigual.doClick();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        addNumber("0");
        btigual.doClick();
    }//GEN-LAST:event_bt0ActionPerformed

    private void btptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btptActionPerformed
        addNumber(".");
        
    }//GEN-LAST:event_btptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    public void addNumber(String digito){
        txtoperacion.setText(txtoperacion.getText()+digito);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btc;
    private javax.swing.JButton btdv;
    private javax.swing.JButton btexp;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmltp;
    private javax.swing.JButton btmn;
    private javax.swing.JButton btprc;
    private javax.swing.JButton btpt;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtoperacion;
    private javax.swing.JLabel txtresultado;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelative(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
